apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: deployment/nginx
          imagePullPolicy: Never
          name: nginx
--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    metallb.universe.tf/allow-shared-ip: key
  name: nginx
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
    -
      name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector: 
    app: nginx
  type: LoadBalancer
