apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress
  name: wordpress
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - 
          image: deployment/wordpress
          imagePullPolicy: Never
          name: wordpress
          livenessProbe:
            exec:
              command:
                - pgrep
                - php-fpm
            initialDelaySeconds: 10
            periodSeconds: 5
--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    metallb.universe.tf/allow-shared-ip: key
  name: wordpress
spec: 
  ports: 
    - 
      name: http
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector: 
    app: wordpress
  type: LoadBalancer
